### ISSUE TITLE
Move the from centos to a public repository

### ISSUE THREAD

**Issue by savmickael** [WorldCereal/classification-docker#1]
If possible can you move please to the public docker image of [centos 8.2](https://hub.docker.com/layers/centos/library/centos/centos8.2.2004/images/sha256-cf4f5cf174e78810379036c53fd6d258d13b3735aa5611b0b61e331a8fedbac6?context=explore)

**Comment by jdries** [comment]
I tried it, but the image failed to build, had to revert to old setup.

```
Step 1/5 : FROM centos:centos8.2.2004
centos8.2.2004: Pulling from library/centos
Digest: sha256:4062bbdd1bb0801b0aa38e0f83dece70fb7a5e9bce223423a68de2d8b784b43b
Status: Downloaded newer image for centos:centos8.2.2004
 ---> 831691599b88
Step 2/5 : LABEL ESA World Cereal Processing Chain
 ---> Running in bf82a4f7cd32
 ---> 5edc06818670
Removing intermediate container bf82a4f7cd32
Step 3/5 : RUN sed -i 's/enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-PowerTools.repo || true &&     yum install -y python38-devel gcc-c++ gdal-devel python3-gdal &&     python3.8 -m pip install -I --upgrade "pip<20.3" &&     python3.8 -m pip install -v --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-packages/simple worldcereal>=0.3.2 &&     rm -rf /root/.cache &&     yum clean all &&     rm -rf /var/cache/yum/*
 ---> Running in 030f8c5b2242
CentOS-8 - AppStream                            1.7 MB/s | 8.8 MB     00:05    
CentOS-8 - Base                                 2.9 MB/s | 6.5 MB     00:02    
CentOS-8 - Extras                                15 kB/s |  10 kB     00:00    
CentOS-8 - PowerTools                           1.5 MB/s | 2.3 MB     00:01    
No match for argument: gdal-devel
No match for argument: python3-gdal
[91mError: Unable to find a match: gdal-devel python3-gdal
[0mThe command '/bin/sh -c sed -i 's/enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-PowerTools.repo || true &&     yum install -y python38-devel gcc-c++ gdal-devel python3-gdal &&     python3.8 -m pip install -I --upgrade "pip<20.3" &&     python3.8 -m pip install -v --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-packages/simple worldcereal>=0.3.2 &&     rm -rf /root/.cache &&     yum clean all &&     rm -rf /var/cache/yum/*' returned a non-zero code: 1
```

**Comment by savmickael** [comment]
I think you need to add epel as packages repository in the docker file :
- https://centos.pkgs.org/8/epel-x86_64/python3-gdal-3.0.4-8.el8.x86_64.rpm.html
- https://centos.pkgs.org/8/epel-x86_64/gdal-devel-3.0.4-8.el8.x86_64.rpm.html

The centos8 version of the vito artifactory seems to have some additional configuration than centos 8 official.

**Comment by jdries** [comment]
Sure, but this is low priority for the moment. Feel free to propose a working dockerfile on another base image.

**Comment by savmickael** [comment]
gdal-dev and python3-gdal are available natively with the version 3.0.4 on Ubuntu 20.04 which is the base image from our side.

**Comment by savmickael** [comment]
I have try to move to ubuntu 20.04 cf. [upgrade_dockerfile branch](https://github.com/WorldCereal/classification-docker/tree/upgrade_dockerfile) and encounter issue with the installation of the worldcereal package (cf. https://github.com/WorldCereal/wc-classification/issues/2)

**Comment by savmickael** [comment]
With my branch you can now build from public repo. You can test with `docker run --rm -it  ewocclassifdocker:latest` it will run `worldcereal -h`

**Comment by savmickael** [comment]
With my branch you can now build from public repo. You can test with `docker run --rm -it  ewocclassifdocker:latest` it will run `worldcereal -h`

**Comment by savmickael** [comment]
close with #2
