### ISSUE TITLE
Fixed zarr version

### ISSUE THREAD

**Issue by Fahdben** [WorldCereal/classification-docker#61]
@savmickael @kvantricht Please note that I had to fix/use a different version of zarr in order to make the worldcereal code work and avoid the deletion error. I also fixed the protobuf version (unrelated with zarr).

https://github.com/WorldCereal/classification-docker/blob/develop/Dockerfile#L55

**Comment by kvantricht** [comment]
Our new jenkins build in python 3.8 also had an issue with protobuf which was at >4.0.0 which is incompatible with tensorflow it seems. I will fix the version at 3.20.0 as in your docker image.
For zarr, you mean you could actually avoid issue mentioned by @savmickael by using different version?
