### ISSUE TITLE
Global Cropland production v2 - Missing realm 8 model

### ISSUE THREAD

**Issue by savmickael** [WorldCereal/classification-docker#68]
The production failed on the tiles which are covered by the realm 8 due to the fact that this one is not provided on VITO artifactory.

Example of log return by the production: 
[04QFJ_block_6_error.log](https://github.com/WorldCereal/classification-docker/files/9899014/04QFJ_block_6_error.log)

**Comment by savmickael** [comment]
@agrosu1978 if possible can you provide the list of tiles with this error please

**Comment by agrosu1978** [comment]
> @agrosu1978 if possible can you provide the list of tiles with this error please

It is not possible to have a list with tiles impacted by this error. Moreover, the process of classification is still running as we speak, so there may be more in the end

**Comment by savmickael** [comment]
> It is not possible to have a list with tiles impacted by this error. Moreover, the process of classification is still running as we speak, so there may be more in the end

as discuss by mail we need to handle this type of return error to track that in the db

**Comment by kvantricht** [comment]
As discussed, we do not have sufficient training data to train dedicated Realm 8 model. We need to choose another realm model and copy it over as if it were a Realm 8 model. It does not require a new release from wc-classification, but probably it does require a new Docker image. What we can do on our end is place a so-called Realm 8 model on the Artifactory which will then be downloaded and added to the new Docker image. Do we need to work on that and ping you once it's done?

**Comment by kvantricht** [comment]
This should have been fixed already in earlier release. Realm 8 is covered by Artifactory.
