### ISSUE TITLE
Global cropmap production V3 - No SAR ARD 

### ISSUE THREAD

**Issue by savmickael** [WorldCereal/classification-docker#84]
During the cropland production V3, the fact that some tile has no S1 ARD generated an error in the classification code. The affected tiles are the following:  01GEL, 01GEM, 12QWF, 27PUT

| Tile id  | Area | Info
|-----:|---------------|-----------|
|     01GEL |   [Chatham_Islands](https://en.wikipedia.org/wiki/Chatham_Islands)            | [01GEL_110.zip](https://github.com/WorldCereal/classification-docker/files/10767416/01GEL_110.zip) |
|      01GEM|      [Chatham_Islands](https://en.wikipedia.org/wiki/Chatham_Islands)       | [01GEM_110.zip](https://github.com/WorldCereal/classification-docker/files/10767407/01GEM_110.zip) |
|     12QWF|     [Socorro_Island ](https://en.wikipedia.org/wiki/Socorro_Island)       | [12QWF_110.zip](https://github.com/WorldCereal/classification-docker/files/10767564/12QWF_110.zip) |
|     27PUT|      Cap Verde      | [27PUT_110.zip](https://github.com/WorldCereal/classification-docker/files/10765965/27PUT_110.zip) |
| 54VUJ | Okhotsky District (Russia) |  [54VUJ_110.zip](https://github.com/WorldCereal/classification-docker/files/10852554/54VUJ_110.zip)  |
| 54VVJ | Okhotsky District (Russia) |  [54VVJ_110.zip](https://github.com/WorldCereal/classification-docker/files/10852557/54VVJ_110.zip)| 
| 54VVK | Okhotsky District (Russia) | [54VVK_110.zip](https://github.com/WorldCereal/classification-docker/files/10852558/54VVK_110.zip)|

**Comment by savmickael** [comment]
@kvantricht  this issue identify the case where we have no SAR data for cropland computation. In this case the classifier code must switch to optical only mode.

**Comment by kvantricht** [comment]
@savmickael I'm working on a fix that allows running the classifier without specifying a SAR collection, in which case it will try to look for an optical-only model to run on. That's the best, if not the only way to handle it from classifier side. It means that on your side, you would need to check if not enough (or no) SAR data is available, the config file is generated without a SAR collection.

**Comment by savmickael** [comment]
@romain-bdc  can you please prepare a function to detect the case where we have no S1 ARD data in the CSV (like for ARD TIR).

**Comment by kvantricht** [comment]
@savmickael @romain-bdc I made a fix in develop that seems to work. It produces a result based on optical-only when no SAR collection is provided in the config file: https://github.com/WorldCereal/wc-classification/commit/60ac937c2e09221999bbcd8581a2420e1d19e502

Let me know how you want to proceed.

**Comment by romain-bdc** [comment]
> @savmickael @romain-bdc I made a fix in develop that seems to work. It produces a result based on optical-only when no SAR collection is provided in the config file: [WorldCereal/wc-classification@60ac937](https://github.com/WorldCereal/wc-classification/commit/60ac937c2e09221999bbcd8581a2420e1d19e502)
> 
> Let me know how you want to proceed.

I pull your changes and I made modifications in ewoc_classif to take in account no sar data at all, I am currently running some tests.

**Comment by romain-bdc** [comment]
@kvantricht When there is no SAR data at all it is working now but the incomplete collsize or maxgap issue still here, indeed in ewoc_classif we check before Filtering collections which reduces sometimes date in collection, I am working on taking in account this filtering in our code.

**Comment by romain-bdc** [comment]
@kvantricht After some tests I managed to filter SAR data as you do in processor for collsize and maxpag/gapend/gapstart issue :) 
For issue #87 with TIR data it should work same and there are still no issue before running processor, as it is done later in processor it needs an other fix on our code, I am on it.

**Comment by kvantricht** [comment]
Thanks for the update!

**Comment by romain-bdc** [comment]
@kvantricht Fix done, it handles case where there is collisize and gap issue for SAR and TIR (hence resolve #84, #85, #87 and #89), waiting for review by Mickaël.

**Comment by romain-bdc** [comment]
Finally those tiles have been deleted from the production tiles list
